"use strict";

/* ---------------------------------------------------------------------------
 * gen-assets.js — generate a static asset registry the app can resolve.
 *
 * React Native's `require()` needs string-literal paths, so we can't load
 * dynamically-named audio/images. This scans content/ for the media that
 * actually exists and emits src/generated/assets.ts mapping
 *   "<dir>/<file>"  ->  require("../../content/<dir>/<file>")
 *
 * Run after rendering (audio/images): `node tools/gen-assets.js` (or
 * `npm run gen-assets`). Re-run whenever media is added.
 * ------------------------------------------------------------------------- */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const CONTENT = path.join(ROOT, "content");
const OUT = path.join(ROOT, "src", "generated", "assets.ts");

const MEDIA = new Set([".mp3", ".png", ".jpg", ".jpeg"]);

function walk(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else if (MEDIA.has(path.extname(entry.name).toLowerCase())) acc.push(full);
  }
  return acc;
}

function main() {
  if (!fs.existsSync(CONTENT)) throw new Error(`No content/ at ${CONTENT}`);
  const files = walk(CONTENT).sort();
  fs.mkdirSync(path.dirname(OUT), { recursive: true });

  const lines = files.map((abs) => {
    const key = path.relative(CONTENT, abs).split(path.sep).join("/");
    const req = "./" + path.relative(path.dirname(OUT), abs).split(path.sep).join("/");
    return `  ${JSON.stringify(key)}: require(${JSON.stringify(req)}),`;
  });

  const out =
    "// AUTO-GENERATED by tools/gen-assets.js — do not edit by hand.\n" +
    "// Maps \"<dir>/<file>\" (relative to content/) to a bundled asset module.\n" +
    "export const assets: Record<string, number> = {\n" +
    lines.join("\n") +
    "\n};\n\n" +
    "export function asset(key?: string | null): number | undefined {\n" +
    "  return key ? assets[key] : undefined;\n" +
    "}\n";

  fs.writeFileSync(OUT, out);
  console.log(`Wrote ${path.relative(ROOT, OUT)} (${files.length} assets).`);
}

main();
